apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clustervis.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clustervis.labels" . | nindent 4 }}
automountServiceAccountToken: true
